version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: birthwish
      MYSQL_USER: birthwish
      MYSQL_PASSWORD: corp_2
      MYSQL_DATABASE_TEST: test_birthwish
      MYSQL_USER_TEST: birthwish
      MYSQL_PASSWORD_TEST: corp_2
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    command: celery -A birthday_wish worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A birthday_wish beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis


volumes:
  mysql_data:
  redis_data:
